### ISSUE TITLE
Update to latest ws

### ISSUE THREAD

**Issue by kumavis** [pull-stream/pull-ws-server#17]
Currently using a dependency pinned to a commit.

Upgrading will help resolve [this patchwork crash](https://github.com/ssbc/patchwork/issues/428) caused by [this ws issue](https://github.com/websockets/ws/issues/778)

The [pinned dependency commit](https://github.com/pull-stream/pull-ws-server/blob/master/package.json#L13) by @dominictarr was merged into upstream, but that method no longer exists on latest.

Breaking changes listed here: https://github.com/websockets/ws/releases/tag/1.0.0

**Comment by mmckegg** [comment]
@kumavis have you tried this out in patchwork to see if it works?

**Comment by kumavis** [comment]
nope, just tracking the issue

**Comment by kumavis** [comment]
Looks like [pull-ws](https://github.com/pull-stream/pull-ws/blob/master/package.json) is already on `1.x.x` 👍

**Comment by dominictarr** [comment]
this repo is no longer necessary, it's merged into pull-ws, we can deprecate and point to pull-ws

**Comment by dominictarr** [comment]
oh, i see patchwork still uses this. okay I'm just gonna merge this.
